---
# Create a snippets folder
- name: Create download folder
  file:
    path: '{{ snippets_path }}'
    state: directory
  
# Create user cloud-init files
# NOTE: The storage used for these files has to support snippets
- name: Create user cloud-init files
  template:
    src: user_template.j2
    dest: '{{ snippets_path }}{{ new_vm_id }}-user.yml'
    owner: root
    group: root
    mode: 0644