---
- name: Install sudo
  apt:
    name: sudo
    state: present

- name: Create new user
  user:
    name: "{{ lcx_username }}"
    password: "{{ lxc_password | password_hash('sha512') }}"
    groups:
      - sudo
      - users
    append: true
    shell: "{{ shell }}"
    update_password: on_create
    state: present

- name: Enable passwordless sudo for "{{ lcx_username }}"
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ lcx_username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"
    state: present

- name: Suppress login message (hushlogin)
  file:
    path: "/home/{{ lcx_username }}/.hushlogin"
    mode: 0644
    owner: "{{ lcx_username }}"
    group: "{{ lcx_username }}"
    modification_time: preserve
    access_time: preserve
    state: touch
