---
# Create a download folder
- name: Create download folder
  file:
    path: '{{ os_image_path }}'
    state: directory

- name: Download cloud-init images
  get_url:
    url: '{{ image_url }}'
    dest: '{{ os_image_path }}{{ cloud_init_file }}'
  