---
- name: Ensure the mount point directory exists
  file:
    path: "{{ mount_direstory }}"
    state: directory

- name: Check if {{ drive_to_mount }} exists and is a block device
  command: lsblk {{ drive_to_mount }}
  register: lsblk_output
  failed_when: lsblk_output.rc != 0
  changed_when: false

- name: Mount the BTRFS filesystem
  mount:
    path: "{{ mount_direstory }}"
    src: "{{ drive_to_mount }}"
    fstype: "{{ drive_format }}"
    opts: defaults
    state: mounted
