---
- name: Remove cloud-init drive
  community.general.proxmox_disk:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ vm_id }}"
    disk: 'ide2'
    state: absent

# Pause before starting VM again
# Without a pause the task may indicate it's already started
# When that happens, the VM doesn't get started
- name: Pause
  pause:
    seconds: 30
