---
# Start VMs
- name: Start VM
  proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ vm_id }}"
    state: 'started'

- name: Pause
  pause:
    seconds: 30
    