---

- name: Create Proxmox KVM virtual machine template
  proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ vm_id }}"
    name: "{{ vm_name }}"
    cores: "{{ vm_cores }}"
    sockets: "{{ vm_sockets }}"
    memory: "{{ vm_memory }}"
    balloon: 0
    bios: "{{ vm_bios }}"
    machine: "{{ vm_machine }}"
    scsihw: "{{ vm_scsihw }}"
    net: 
      net0: "virtio,bridge={{ vm_bridge }},firewall=1"
    ipconfig:
      ipconfig0: "ip={{ new_vm_ip_address }}/24,gw={{ vm_ip_gateway }}"
    efidisk0:
      storage: "{{ vm_storage }}"
      format: raw
      efitype: 4m
      pre_enrolled_keys: 1
    storage: "{{ vm_storage }}"
    scsi:
      scsi0: '{{ vm_storage }}:0,import-from={{ image_storage }}:0/{{ image_file }},format={{ drive_format }},iothread=1'
    ide:
      ide2: '{{ vm_storage }}:cloudinit'
    ostype: "{{ vm_os_type }}"
    onboot: 'no'
    cpu: 'host'
    boot: order=scsi0
    cicustom: 'user={{ snippets_storage }}:snippets/{{ vm_id }}-user.yml'
    agent: 'enabled=1'
    vga: "{{ vm_vga }}"
    serial: '{"{{ vm_vga }}":"socket"}'
    timeout: 700
    state: present

