---

- include_tasks: install_required_packages.yml
- include_tasks: create_vm_template.yml
# - include_tasks: update_network_settings.yml
- include_tasks: resize_disk.yml
- include_tasks: start_vm.yml
